spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor?serverTimezone=America/Sao_Paulo
    username: root
    password: Thi@g0Root
  jpa:
    hibernate:
      ddl-auto: create
      spring:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
